### ISSUE TITLE
How to pass data between view controllers?

### ISSUE THREAD

**Issue by Gargo** [Quen98/CoordinatorDrivenNavigation#4]
Tried to add params to `AppFlowStep` from your example - it is not possible because
`Enum with raw type cannot have cases with arguments`

**Comment by Quen98** [comment]
There's an optional parameter called "param" that you can specify when triggering a push/pull/pop/etc.
This param is forwarded to the newViewControllerOrCoordinatorForStep() function

eg:
push(step: .myStep, param: theParametersYouWantToPassToYourNextVC)

Having the possibility to have params in the enums is on my todo list, but I can't give an estimation for when it will be implemented
